### ISSUE TITLE
player_health_info not working to a good degree

### ISSUE THREAD

**Issue by SCPeach** [Exiled-Team/Common-Utils#102]
player_health_info works to a degree but very poorly

Health info of a player being looked at doesn't update for a viewer until they look away and look back again, it only really seems to update whenever damage is taken too. It doesn't fix itself when you use medical items, when healed via plugin means, and sometimes randomly changes the Max HP part of the info despite the Max HP not actually changing

**Server logs**
https://pastebin.com/24xgkpiW

**Copy of current CU config section**
https://pastebin.com/7Sg3nHBR

**EXILED Version ("latest" is not a version):**
5.3.0

**Results of `show plugins` command in console:**
https://pastebin.com/cXUTE6qQ

**Comment by joker-119** [comment]
It not updating until you look away and look back is a client thing and to be expected. The value for health / max health will be updated anytime they take damage, this is because updating their info string too frequently causes ratelimiting on the client side and once triggered they would go an extended period with no update at all.

As for the max health value changing, that's either due to a plugin or base game issue, as that property value is pulled directly from base game code anytime its displayed
