### ISSUE TITLE
914 Teleport section does not induce damage requested

### ISSUE THREAD

**Issue by TheRecyclingBin** [Exiled-Team/Common-Utils#78]
As of recently, Common utils was updated so that you could have seperate options for rooms to have 914 teleport you to and have it give different status effects and damage values. However, despite everything else working for me, the teleports aren't damaging me at all despite changing all options to do 75 damage.

1. Go to 914
2. Go in on "Rough" as this was the setting I selected in the config
3. Plugin respectively teleports me to any rooms I requested and gives me the requested status effects but does not do 75 damage as I requested

**Expected behavior**
You know at this point, it's supposed to hurt people.

**Server logs**
I can't seem to find it in the local admin logs sorry

**Copy of current CU config section**
https://pastebin.com/3mGy04Wc

**EXILED Version ("latest" is not a version):**
3.2.1

**Results of `show plugins` command in console:**
https://pastebin.com/QB3UHt14

**Additional context**
If it isn't a pain or too much to ask for. I think there should be an option for percentage based damage so SCPs can pay a price to teleport as 75 damage wouldn't really do much, and nothing at all if they have a hume shield

**Comment by joker-119** [comment]
Please try to replicate this bug with CU 4.3.0 with the debug config enabled, if it still happens re-port your CU config section and include the localadmin/multiadmin logs please.

**Comment by JustJesseGITHUB** [comment]
Example of what he is saying
ClassD with 50 HP, when the configuration for 914 teleportation is set, and set to any percentage value ect. 0.5 it takes away 50 health not 50%.

**Comment by JustJesseGITHUB** [comment]
Easily replicated by using the sethp command in RA and using 0.5 for your damage on 914 teleport config

**Comment by joker-119** [comment]
That isn't at all the same issue that he is reporting here.

**Comment by JustJesseGITHUB** [comment]
i set my config to 0.5 for teleport i have ClassD default health at 110HP and it took all 110HP away when i tried teleporting out with 914

**Comment by JustJesseGITHUB** [comment]
this technically relates to the same issue he is having because it is doing more damage than the requested amount

**Comment by JustJesseGITHUB** [comment]
here is an example for you of what happens with all values from 0.1 to 0.9 https://gyazo.com/fa529c54136355f0a7854ef4b993da68

**Comment by JustJesseGITHUB** [comment]
new update still doesnt work

**Comment by JustJesseGITHUB** [comment]
you need it to check the max health and current health so it cand determine how much to take away if the player is lower than max health

**Comment by joker-119** [comment]
Firstly, your issue is not at all the same as his issue. His is it did no damage at all. Yours is it does too much.
Secondly, The new version was tested and verified to work by 3 people including myself.
Thirdly, Recordings and screenshots are absolutely, enteirly and utterly useless to me in every possibly conceivable way. Provide your server logs with debug enabled, and a pastebin of your CU config section.

Lastly, Why would i need to check current and max health both? That makes no sense at all. It's meant to always take a % of max health, using their current health was a design oversight I made originally, if you want to have an option for % of current health, make a feature request for that option to be added.
